analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore

custom_lint:
  enable_all_lint_rules: false
  debug: true,
  verbose: true,
  rules:
    - newline_before_return

linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - avoid_print
    - prefer_final_fields
    - prefer_const_constructors
    - prefer_null_aware_operators
    - unnecessary_new
    - sort_constructors_first
    - prefer_single_quotes
    - require_trailing_commas
